version: '3'

services:
    quiz-builder-database:
        image: postgres
        container_name: quiz-builder-database
        environment:
            - POSTGRES_USER=quizbuilder_user
            - POSTGRES_PASSWORD=quizbuilder_password
            - POSTGRES_DB=quizbuilder
        volumes:
            - database-volume:/var/lib/postgresql/data
        ports:
            - '5432:5432'
        networks:
            - shared-network
        restart: on-failure
    quiz-builder-database-test:
        image: postgres
        container_name: quiz-builder-database-test
        environment:
            - POSTGRES_USER=quizbuilder_user
            - POSTGRES_PASSWORD=quizbuilder_password
            - POSTGRES_DB=quizbuilder
        volumes:
            - database-volume-test:/var/lib/postgresql/data
        ports:
            - '5430:5432'
        networks:
            - shared-network
        restart: on-failure
    quiz-builder-api:
        depends_on:
            - quiz-builder-database
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./:/app
        container_name: quiz-builder-api
        expose:
            - '4000'
        ports:
            - '4000:4000'
        command: sh -c "npm run $NPM_SCRIPT"
        networks:
            - shared-network

volumes:
    database-volume:
    database-volume-test:

networks:
    shared-network:
